### ISSUE TITLE
Links from embeds doesn't show on Messenger

### ISSUE THREAD

**Issue by Bjornskjald** [Bjornskjald/messenger-discord#69]

**Comment by Bjornskjald** [comment]
https://discord.js.org/#/docs/main/stable/class/MessageEmbed?scrollTo=url

**Comment by Bjornskjald** [comment]
@talormanda I think it works, can you try it?

**Comment by talormanda** [comment]
@Bjornskjald it works. youre the best!

**Comment by talormanda** [comment]
![untitled](https://user-images.githubusercontent.com/10092964/36701295-d34c8fd0-1b20-11e8-89ae-c0f0fc9138d3.png)

Here is how it looks if you are wondering. I like it. Hope you are happy with it also.

**Comment by talormanda** [comment]
![untitled](https://user-images.githubusercontent.com/10092964/36701295-d34c8fd0-1b20-11e8-89ae-c0f0fc9138d3.png)

Here is how it looks if you are wondering. I like it. Hope you are happy with it also. @Bjornskjald

**Comment by Bjornskjald** [comment]
@talormanda Can I take this screenshot to the upcoming official site?

**Comment by talormanda** [comment]
@Bjornskjald how about we make a better one?

**Comment by Bjornskjald** [comment]
I already made something like this: 
![image](https://user-images.githubusercontent.com/26630168/37048066-115f10ca-216d-11e8-93f4-658da2c8a9e9.png)

**Comment by talormanda** [comment]
@Bjornskjald I redid the photos because I have a custom name on discord and it doesn't translate over onto Facebook as you can see one is called HuntrBot and the other Pokemon. My OCD. You can use whichever, I just wanted to provide a more accurate option. You can also probably post this on the silph road (pokemon go subreddit) and you'd probably get a lot of people using it really fast. https://www.reddit.com/r/TheSilphRoad/ (when you finish the website)

**Comment by Bjornskjald** [comment]
![obraz](https://user-images.githubusercontent.com/26630168/37049214-87a45d14-2170-11e8-8ef6-3683305123e4.png)
Fixed it
